spring:
  profiles:
    active: default

  application:
    name: elasticSearch
    #es 配置
  elasticsearch:
    uris: http://localhost:19200
    socket-timeout: 3000
    connection-timeout: 500

server:
  port: 8200



